name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: 1nxeo/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 46c82c227681bf77ddcd8c7ad5d651df
          TIMEZONE: Asia/Seoul
